export const getHelpMessage = () =>
  [
    "ManagerOps Bot - Quick Commands",
    "",
    "/start - Start the bot",
    "/help - Show this command list",
    "/guide - Full instructions with examples",
    "/status - Check system status",
    "/projects - View projects",
    "/tasks - View tasks",
    "/payments - View payments",
    "/providers - View providers",
    "/documents - View documents",
    "/today - View today's priorities",
    "/report - Generate a summary report",
    "",
    "Add new records:",
    "/addtask - Add a new task",
    "/addpayment - Add a new payment",
    "/addproject - Add a new project",
    "/addprovider - Add a new provider",
    "",
    "Tip:",
    "Telegram commands do not use spaces.",
    "Use /addtask, not /add task.",
    "Use /addpayment, not /add payment.",
  ].join("\n");

export const GUIDE_MESSAGES = [
  [
    "ManagerOps Telegram Bot - User Guide",
    "",
    "This bot helps you manage projects, tasks, payments, providers, documents, and daily priorities from Telegram.",
    "",
    "Basic commands:",
    "/start - Start the bot",
    "/help - Quick command list",
    "/guide - Full instructions",
    "/manual - Same full instructions",
    "/instructions - Same full instructions",
    "/status - Check current status",
    "",
    "View information:",
    "/projects - View active projects",
    "/tasks - View pending tasks",
    "/payments - View payments",
    "/providers - View providers",
    "/documents - View documents",
    "/today - View today's priorities",
    "/report - Generate a summary report",
  ].join("\n"),
  [
    "Adding Tasks",
    "",
    "Use /addtask when something needs to be done.",
    "",
    "Examples:",
    "/addtask Pay VectorFire Systems $890 today, urgent, avoid compliance delay",
    "/addtask Call supplier about conveyor belt delivery tomorrow, high priority",
    "/addtask Review welding photos before releasing final payment, due Friday",
    "/addtask Ask Lone Star Electrical for updated W-9 before payment release, urgent",
    "",
    "Best format:",
    "/addtask [what needs to be done], [priority], [due date], [extra details]",
  ].join("\n"),
  [
    "Adding Payments",
    "",
    "Use /addpayment for money owed, paid, pending, or approved.",
    "",
    "Examples:",
    "/addpayment VectorFire Systems invoice for $890 due today, urgent",
    "/addpayment Precision Welding deposit $1,950 paid today, balance pending QA approval",
    "/addpayment Lone Star Electrical $2,380 pending W-9 before release",
    "/addpayment Conveyor belt supplier $4,500 awaiting approval",
    "",
    "Best format:",
    "/addpayment [provider/vendor], [amount], [status], [due date], [notes]",
  ].join("\n"),
  [
    "Adding Projects",
    "",
    "Use /addproject for a larger job or work area.",
    "",
    "Examples:",
    "/addproject Warehouse Conveyor Repair, high priority, customer needs line running by Friday",
    "/addproject Office Electrical Upgrade, waiting for provider quote and approval",
    "/addproject Stainless Steel Material Order, tracking supplier pricing and delivery",
    "/addproject Fire Safety Compliance, urgent, payment and inspection required this week",
    "",
    "Best format:",
    "/addproject [project name], [status], [priority], [important notes]",
  ].join("\n"),
  [
    "Adding Providers",
    "",
    "Use /addprovider for a vendor, supplier, contractor, or company.",
    "",
    "Examples:",
    "/addprovider VectorFire Systems, fire safety service, handles compliance inspections",
    "/addprovider Precision Welding & Fabrication, welding contractor, used for fabrication repairs",
    "/addprovider Lone Star Electrical Controls, electrical contractor, needs updated W-9",
    "/addprovider NorthBridge Calibration, calibration provider, sends calibration certificates",
    "",
    "Best format:",
    "/addprovider [company name], [service type], [contact info if available], [notes]",
  ].join("\n"),
  [
    "Daily Workflow",
    "",
    "1. Start the day with /today",
    "2. Check pending tasks with /tasks",
    "3. Add new tasks with /addtask",
    "4. Add payments with /addpayment",
    "5. End the day with /report",
    "",
    "Example daily use:",
    "/today",
    "/tasks",
    "/addtask Call Precision Welding for installation photos today, high priority",
    "/addpayment Precision Welding $1,950 deposit paid today, balance pending QA approval",
    "/report",
    "",
    "Common mistakes:",
    "Use /tasks, not /task.",
    "Use /addtask, not /add task.",
    "Use /addpayment, not /add payment.",
    "Telegram commands should not have spaces inside the command.",
  ].join("\n"),
];

export const getGuideMessages = () => GUIDE_MESSAGES;
